//Reset Store
export const RESET_STORE = "RESET_STORE";

// UI Action Types
export const UI_START_PROCESS = "UI_START_PROCESS";
export const UI_STOP_PROCESS = "UI_STOP_PROCESS";

// Auth Action Types
export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_FETCH_START = "AUTH_FETCH_START";
export const AUTH_FETCH_END = "AUTH_FETCH_END";

// Device Action Type
export const SET_DEVICE_LIST = "SET_DEVICE_LIST";
export const SET_SELECTED_DEVICE = "SET_SELECTED_DEVICE";
export const DEVICE_FETCH_START = "DEVICE_FETCH_START";
export const DEVICE_FETCH_END = "DEVICE_FETCH_END";
export const SET_SELECTED_DEVICE_POSITION = "SET_SELECTED_DEVICE_POSITION";
export const DEVICE_POSITION_FETCH_START = "DEVICE_POSITION_FETCH_START";
export const DEVICE_POSITION_FETCH_END = "DEVICE_POSITION_FETCH_END";
export const DEVICE_UPDATE_START = "DEVICE_UPDATE_START";
export const DEVICE_UPDATE_END = "DEVICE_UPDATE_END";

// Group Action Type
export const SET_GROUP_LIST = "SET_GROUP_LIST";
export const SET_SELECTED_GROUP = "SET_SELECTED_GROUP";
export const GROUP_FETCH_START = "GROUP_FETCH_START";
export const GROUP_FETCH_END = "GROUP_FETCH_END";


// User Action Type
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const USER_FETCH_START = "USER_FETCH_START";
export const USER_FETCH_END = "USER_FETCH_END";

// Position Action Type
export const POSITION_FETCH_START = "POSITION_FETCH_START";
export const POSITION_FETCH_END = "POSITION_FETCH_END";

// Report Action Type
export const SET_REPORT_FROM_DATE_TIME = "SET_REPORT_FROM_DATE_TIME";
export const SET_REPORT_TO_DATE_TIME = "SET_REPORT_TO_DATE_TIME";
export const REPORT_FETCH_START = "REPORT_FETCH_START";
export const REPORT_FETCH_END = "REPORT_FETCH_END";

// Report Position Action Type
export const SET_REPORT_POSITION_LIST = "SET_REPORT_POSITION_LIST";
export const REPORT_POSITION_FETCH_START = "REPORT_POSITION_FETCH_START";
export const REPORT_POSITION_FETCH_END = "REPORT_POSITION_FETCH_END";

// Report Event Action Type
export const SET_REPORT_EVENT_LIST = "SET_REPORT_EVENT_LIST";
export const REPORT_EVENT_FETCH_START = "REPORT_EVENT_FETCH_START";
export const REPORT_EVENT_FETCH_END = "REPORT_EVENT_FETCH_END";

// Report ReportSummary Action Type
export const SET_REPORT_REPORT_SUMMARY_LIST = "SET_REPORT_REPORT_SUMMARY_LIST";
export const REPORT_REPORT_SUMMARY_FETCH_START = "REPORT_REPORT_SUMMARY_FETCH_START";
export const REPORT_REPORT_SUMMARY_FETCH_END = "REPORT_REPORT_SUMMARY_FETCH_END";

// Report ReportTrip Action Type
export const SET_REPORT_REPORT_TRIP_LIST = "SET_REPORT_REPORT_TRIP_LIST";
export const REPORT_REPORT_TRIP_FETCH_START = "REPORT_REPORT_TRIP_FETCH_START";
export const REPORT_REPORT_TRIP_FETCH_END = "REPORT_REPORT_TRIP_FETCH_END";

// Report Report Stop Action Type
export const SET_REPORT_REPORT_STOP_LIST = "SET_REPORT_REPORT_STOP_LIST";
export const REPORT_REPORT_STOP_FETCH_START = "REPORT_REPORT_STOP_FETCH_START";
export const REPORT_REPORT_STOP_FETCH_END = "REPORT_REPORT_STOP_FETCH_END";

// Command Action Type
export const COMMAND_DISPATCH_START = "COMMAND_DISPATCH_START";
export const COMMAND_DISPATCH_END = "COMMAND_DISPATCH_END";

// Geofence Action Type
export const SET_GEOFENCE_LIST = "SET_GEOFENCE_LIST";
export const GEOFENCE_FETCH_START = "GEOFENCE_FETCH_START";
export const GEOFENCE_FETCH_END = "GEOFENCE_FETCH_END";

// Setting Action Type
export const SET_SETTING = "SET_SETTING";